FUNCTION ZFI_POSTING_DOCUMENT_BAPI.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(ES_CONF) TYPE  ZFI_DOCUMENT_POSTING_CNF
*"  EXPORTING
*"     REFERENCE(I_RETURN) TYPE  ZFI_DOCUMENT_POSTING_EXPORT
*"  TABLES
*"      T_BBKPF STRUCTURE  BBKPF
*"      T_BBSEG STRUCTURE  BBSEG
*"      T_EXTENSION2 STRUCTURE  BAPIPAREX OPTIONAL
*"      T_RETURN STRUCTURE  BAPIRET2 OPTIONAL
*"----------------------------------------------------------------------

*&---------------------------------------------------------------------*
* Function Name     : Z_FI_DOCUMENT_POSTING_BAPI
* Program Purpose  : Z_FI_DOCUMENT_POSTING_BAPI
* Author           : SUN HUIMING
* Date Written     : 2014/12/04
* Note             : N/A
*&---------------------------------------------------------------------*
*  defined local variable
  DATA: LV_OBJ_KEY TYPE BAPIACHE09-OBJ_KEY.
  DATA: LS_RETURN TYPE BAPIRET2.
  DATA: LV_ITEM TYPE POSNR_ACC VALUE '0000000000'.
  DATA: LS_BBKPF TYPE BBKPF.
  DATA: LS_BBSEG TYPE BBSEG.

*  CLEAR GLOBE VARIABLE
  PERFORM FRM_CLEAR_GLOBE_VARIABLE.

*  assignment input fields to globe variable
  GS_CONF = ES_CONF.
  GT_BBKPF[] = T_BBKPF[].
  GT_BBSEG[] = T_BBSEG[].
  GT_EXT2[] = T_EXTENSION2[].
*  read & process document headr info.
  READ TABLE GT_BBKPF INTO LS_BBKPF INDEX 1.

*  check&process input data
  PERFORM FRM_CHECK_INPUT_DATA USING LS_BBKPF CHANGING T_RETURN[].

  CHECK GT_RETURN[] IS INITIAL AND T_RETURN[] IS INITIAL.

  PERFORM FRM_PROCESS_DOC_HEADER USING LS_BBKPF.

*  read & process item info.
  LOOP AT GT_BBSEG INTO LS_BBSEG.

    LV_ITEM = LV_ITEM + 1. "item value

    PERFORM FRM_PROCESS_GL_ACCOUNTS USING LS_BBSEG LS_BBKPF CHANGING LV_ITEM.

    PERFORM FRM_PROCESS_ACCOUNTPAYABLE USING LS_BBSEG LS_BBKPF CHANGING LV_ITEM.

    PERFORM FRM_PROCESS_ACCOUNTRECEIVABLE USING LS_BBSEG LS_BBKPF CHANGING LV_ITEM.

    PERFORM FRM_PROCESS_CURRENCY_AMT USING LS_BBSEG LS_BBKPF CHANGING LV_ITEM.

    PERFORM FRM_PROCESS_PROCESS_TAX USING LS_BBSEG LS_BBKPF CHANGING LV_ITEM.

    PERFORM FRM_PROCESS_EXTENSION2 USING LS_BBSEG LS_BBKPF LV_ITEM.

*    PERFORM FRM_PROCESS_CRITERIA USING LS_BBSEG LS_BBKPF LV_ITEM.

    CLEAR:LS_BBSEG.
  ENDLOOP.


  CALL FUNCTION 'BAPI_ACC_DOCUMENT_CHECK'
    EXPORTING
      DOCUMENTHEADER    = GS_DOCUMENTHEADER
    TABLES
      ACCOUNTGL         = GT_ACCOUNTGL[]
      ACCOUNTRECEIVABLE = GT_ACCOUNTRECEIVABLE[]
      ACCOUNTPAYABLE    = GT_ACCOUNTPAYABLE[]
      CURRENCYAMOUNT    = GT_CURRENCYAMOUNT[]
      ACCOUNTTAX        = GT_ACCOUNTTAX[]
      CRITERIA          = GT_CRITERIA[]
      RETURN            = GT_RETURN[]
      EXTENSION2        = GT_EXT2[].


  READ TABLE GT_RETURN INTO LS_RETURN WITH KEY TYPE = 'E'.
  IF SY-SUBRC = 0.
    T_RETURN[] = GT_RETURN[].
    I_RETURN-TYPE    = 'E'.
  ELSE.
*  posting financial document
    REFRESH:GT_RETURN[].
    CALL FUNCTION 'BAPI_ACC_DOCUMENT_POST'
  EXPORTING
    DOCUMENTHEADER    = GS_DOCUMENTHEADER
  IMPORTING
*     OBJ_TYPE          =
    OBJ_KEY           = LV_OBJ_KEY
*     OBJ_SYS           =
  TABLES
    ACCOUNTGL         = GT_ACCOUNTGL[]
    ACCOUNTRECEIVABLE = GT_ACCOUNTRECEIVABLE[]
    ACCOUNTPAYABLE    = GT_ACCOUNTPAYABLE[]
    CURRENCYAMOUNT    = GT_CURRENCYAMOUNT[]
    ACCOUNTTAX        = GT_ACCOUNTTAX[]
    CRITERIA          = GT_CRITERIA[]
    RETURN            = GT_RETURN[]
    EXTENSION2        = GT_EXT2[]
    .

    I_RETURN-BELNR   = LV_OBJ_KEY+0(10).
    I_RETURN-BUKRS   = LV_OBJ_KEY+10(4).
    I_RETURN-GJAHR   = LV_OBJ_KEY+14(4).
    I_RETURN-TYPE    = 'S'.

    CALL FUNCTION 'BAPI_TRANSACTION_COMMIT'
      EXPORTING
        WAIT = 'X'.
    T_RETURN[] = GT_RETURN[].
  ENDIF.




ENDFUNCTION.
