FUNCTION ZFI_REVERSE_POSTING_DOCUMENT.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(BUKRS) TYPE  VBKPF-BUKRS DEFAULT '1000'
*"     VALUE(BELNR) TYPE  VBKPF-BELNR
*"     VALUE(GJAHR) TYPE  VBKPF-GJAHR DEFAULT '2022'
*"     VALUE(REASON_REV) TYPE  STGRD DEFAULT '03'
*"  EXPORTING
*"     REFERENCE(I_RETURN) TYPE  ZFI_DOCUMENT_POSTING_EXPORT
*"  TABLES
*"      T_RETURN STRUCTURE  BAPIRET2
*"----------------------------------------------------------------------



  DATA: WA_BAPIDOCHDRR TYPE BAPIACREV.
  DATA: LS_BKPF TYPE BKPF.
  DATA: LS_RETURN TYPE BAPIRET2.
  DATA: LT_RETURN LIKE BAPIRET2.

  SELECT SINGLE *
    FROM BKPF
    INTO LS_BKPF
    WHERE BELNR = BELNR
    AND BUKRS = BUKRS
    AND GJAHR = GJAHR
    AND XREVERSAL = ''
    .
  CHECK LS_BKPF-BELNR IS NOT INITIAL.
*   给 BAPI 函数相应的参数赋值
  WA_BAPIDOCHDRR-OBJ_TYPE     = LS_BKPF-AWTYP.
  WA_BAPIDOCHDRR-OBJ_KEY      = LS_BKPF-AWKEY.
  WA_BAPIDOCHDRR-OBJ_KEY_R    = LS_BKPF-AWKEY.
  WA_BAPIDOCHDRR-PSTNG_DATE   = LS_BKPF-BUDAT.
  WA_BAPIDOCHDRR-FIS_PERIOD   = LS_BKPF-MONAT.
  WA_BAPIDOCHDRR-COMP_CODE    = LS_BKPF-BUKRS.
  WA_BAPIDOCHDRR-AC_DOC_NO    = LS_BKPF-BELNR.
  WA_BAPIDOCHDRR-REASON_REV   = REASON_REV.
*   取得系统 LOGICAL SYSTEM
  CALL FUNCTION 'OWN_LOGICAL_SYSTEM_GET'
    IMPORTING
      OWN_LOGICAL_SYSTEM = WA_BAPIDOCHDRR-OBJ_SYS.
*   调用 BAPI 函数，冲销会计凭证
  CALL FUNCTION 'BAPI_ACC_DOCUMENT_REV_POST'
*      EXPORTING
*        obj_type = gv_glvor
    EXPORTING
      REVERSAL = WA_BAPIDOCHDRR
      BUS_ACT  = LS_BKPF-GLVOR
    TABLES
      RETURN   = T_RETURN.


  READ TABLE T_RETURN WITH KEY TYPE = 'E'.
  IF SY-SUBRC NE 0.
*     提交凭证过账
    CALL FUNCTION 'BAPI_TRANSACTION_COMMIT'
      EXPORTING
        WAIT   = 'X'
      IMPORTING
        RETURN = LS_RETURN.
*
    IF LT_RETURN IS INITIAL.
      LS_RETURN-TYPE = 'S'.
      CONCATENATE '凭证' BELNR GJAHR '冲销成功！' INTO LS_RETURN-MESSAGE.
    ENDIF.
  ELSE.
    CALL FUNCTION 'BAPI_TRANSACTION_ROLLBACK'.
  ENDIF.

  APPEND LS_RETURN TO T_RETURN.
  LOOP AT T_RETURN.
    I_RETURN-TYPE = T_RETURN-TYPE.
    CONCATENATE T_RETURN-MESSAGE I_RETURN-MESSAGE INTO I_RETURN-MESSAGE.
    IF I_RETURN-TYPE = 'S'.

      SELECT SINGLE STBLG STJAH
        FROM BKPF
        INTO (I_RETURN-BELNR,I_RETURN-GJAHR)
        WHERE BELNR = BELNR
        AND BUKRS = BUKRS
        AND GJAHR = GJAHR
        .
      I_RETURN-BUKRS = BUKRS.

    ENDIF.
  ENDLOOP.

  IF I_RETURN-TYPE = 'S'.
    CONCATENATE '冲销凭证号' I_RETURN-BELNR I_RETURN-GJAHR  INTO LS_RETURN-MESSAGE.
    APPEND LS_RETURN TO T_RETURN.
  ENDIF.




ENDFUNCTION.
